/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataExecution;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiCreateExecutionResponse
 */
public class ApiCreateExecutionResponseTest {
    private final ApiCreateExecutionResponse model = new ApiCreateExecutionResponse();

    /**
     * Model tests for ApiCreateExecutionResponse
     */
    @Test
    public void testApiCreateExecutionResponse() {
        // TODO: test ApiCreateExecutionResponse
    }

    /**
     * Test the property 'execution'
     */
    @Test
    public void executionTest() {
        // TODO: test execution
    }

}
