/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataArtifact;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiGetArtifactResponse
 */
public class ApiGetArtifactResponseTest {
    private final ApiGetArtifactResponse model = new ApiGetArtifactResponse();

    /**
     * Model tests for ApiGetArtifactResponse
     */
    @Test
    public void testApiGetArtifactResponse() {
        // TODO: test ApiGetArtifactResponse
    }

    /**
     * Test the property 'artifact'
     */
    @Test
    public void artifactTest() {
        // TODO: test artifact
    }

}
