/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataArtifactType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiGetArtifactTypeResponse
 */
public class ApiGetArtifactTypeResponseTest {
    private final ApiGetArtifactTypeResponse model = new ApiGetArtifactTypeResponse();

    /**
     * Model tests for ApiGetArtifactTypeResponse
     */
    @Test
    public void testApiGetArtifactTypeResponse() {
        // TODO: test ApiGetArtifactTypeResponse
    }

    /**
     * Test the property 'artifactType'
     */
    @Test
    public void artifactTypeTest() {
        // TODO: test artifactType
    }

}
