/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataExecutionType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiUpdateExecutionTypeResponse
 */
public class ApiUpdateExecutionTypeResponseTest {
    private final ApiUpdateExecutionTypeResponse model = new ApiUpdateExecutionTypeResponse();

    /**
     * Model tests for ApiUpdateExecutionTypeResponse
     */
    @Test
    public void testApiUpdateExecutionTypeResponse() {
        // TODO: test ApiUpdateExecutionTypeResponse
    }

    /**
     * Test the property 'executionType'
     */
    @Test
    public void executionTypeTest() {
        // TODO: test executionType
    }

}
