/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.MlMetadataArtifactStructType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MlMetadataDictArtifactStructType
 */
public class MlMetadataDictArtifactStructTypeTest {
    private final MlMetadataDictArtifactStructType model = new MlMetadataDictArtifactStructType();

    /**
     * Model tests for MlMetadataDictArtifactStructType
     */
    @Test
    public void testMlMetadataDictArtifactStructType() {
        // TODO: test MlMetadataDictArtifactStructType
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'noneTypeNotRequired'
     */
    @Test
    public void noneTypeNotRequiredTest() {
        // TODO: test noneTypeNotRequired
    }

    /**
     * Test the property 'extraPropertiesType'
     */
    @Test
    public void extraPropertiesTypeTest() {
        // TODO: test extraPropertiesType
    }

}
