/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.EventPath;
import org.openapitools.client.model.MlMetadataEventType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MlMetadataEvent
 */
public class MlMetadataEventTest {
    private final MlMetadataEvent model = new MlMetadataEvent();

    /**
     * Model tests for MlMetadataEvent
     */
    @Test
    public void testMlMetadataEvent() {
        // TODO: test MlMetadataEvent
    }

    /**
     * Test the property 'artifactId'
     */
    @Test
    public void artifactIdTest() {
        // TODO: test artifactId
    }

    /**
     * Test the property 'executionId'
     */
    @Test
    public void executionIdTest() {
        // TODO: test executionId
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'millisecondsSinceEpoch'
     */
    @Test
    public void millisecondsSinceEpochTest() {
        // TODO: test millisecondsSinceEpoch
    }

}
