/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MlMetadataValue
 */
public class MlMetadataValueTest {
    private final MlMetadataValue model = new MlMetadataValue();

    /**
     * Model tests for MlMetadataValue
     */
    @Test
    public void testMlMetadataValue() {
        // TODO: test MlMetadataValue
    }

    /**
     * Test the property 'intValue'
     */
    @Test
    public void intValueTest() {
        // TODO: test intValue
    }

    /**
     * Test the property 'doubleValue'
     */
    @Test
    public void doubleValueTest() {
        // TODO: test doubleValue
    }

    /**
     * Test the property 'stringValue'
     */
    @Test
    public void stringValueTest() {
        // TODO: test stringValue
    }

}
