/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MlMetadataExecutionState
 */
public class MlMetadataExecutionStateTest {
    /**
     * Model tests for MlMetadataExecutionState
     */
    @Test
    public void testMlMetadataExecutionState() {
        // TODO: test MlMetadataExecutionState
    }

}
