/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataArtifactType;

/**
 * ApiCreateArtifactTypeResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiCreateArtifactTypeResponse {
  public static final String SERIALIZED_NAME_ARTIFACT_TYPE = "artifact_type";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_TYPE)
  private MlMetadataArtifactType artifactType = null;

  public ApiCreateArtifactTypeResponse artifactType(MlMetadataArtifactType artifactType) {
    this.artifactType = artifactType;
    return this;
  }

   /**
   * Get artifactType
   * @return artifactType
  **/
  @ApiModelProperty(value = "")
  public MlMetadataArtifactType getArtifactType() {
    return artifactType;
  }

  public void setArtifactType(MlMetadataArtifactType artifactType) {
    this.artifactType = artifactType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCreateArtifactTypeResponse apiCreateArtifactTypeResponse = (ApiCreateArtifactTypeResponse) o;
    return Objects.equals(this.artifactType, apiCreateArtifactTypeResponse.artifactType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCreateArtifactTypeResponse {\n");
    sb.append("    artifactType: ").append(toIndentedString(artifactType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

