/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MlMetadataExecution;

/**
 * ApiListExecutionsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiListExecutionsResponse {
  public static final String SERIALIZED_NAME_EXECUTIONS = "executions";
  @SerializedName(SERIALIZED_NAME_EXECUTIONS)
  private List<MlMetadataExecution> executions = new ArrayList<MlMetadataExecution>();

  public ApiListExecutionsResponse executions(List<MlMetadataExecution> executions) {
    this.executions = executions;
    return this;
  }

  public ApiListExecutionsResponse addExecutionsItem(MlMetadataExecution executionsItem) {
    if (this.executions == null) {
      this.executions = new ArrayList<MlMetadataExecution>();
    }
    this.executions.add(executionsItem);
    return this;
  }

   /**
   * Get executions
   * @return executions
  **/
  @ApiModelProperty(value = "")
  public List<MlMetadataExecution> getExecutions() {
    return executions;
  }

  public void setExecutions(List<MlMetadataExecution> executions) {
    this.executions = executions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListExecutionsResponse apiListExecutionsResponse = (ApiListExecutionsResponse) o;
    return Objects.equals(this.executions, apiListExecutionsResponse.executions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListExecutionsResponse {\n");
    sb.append("    executions: ").append(toIndentedString(executions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

