/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MlMetadataArtifactType;

/**
 * ApiListArtifactTypesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiListArtifactTypesResponse {
  public static final String SERIALIZED_NAME_ARTIFACT_TYPES = "artifact_types";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_TYPES)
  private List<MlMetadataArtifactType> artifactTypes = new ArrayList<MlMetadataArtifactType>();

  public ApiListArtifactTypesResponse artifactTypes(List<MlMetadataArtifactType> artifactTypes) {
    this.artifactTypes = artifactTypes;
    return this;
  }

  public ApiListArtifactTypesResponse addArtifactTypesItem(MlMetadataArtifactType artifactTypesItem) {
    if (this.artifactTypes == null) {
      this.artifactTypes = new ArrayList<MlMetadataArtifactType>();
    }
    this.artifactTypes.add(artifactTypesItem);
    return this;
  }

   /**
   * Get artifactTypes
   * @return artifactTypes
  **/
  @ApiModelProperty(value = "")
  public List<MlMetadataArtifactType> getArtifactTypes() {
    return artifactTypes;
  }

  public void setArtifactTypes(List<MlMetadataArtifactType> artifactTypes) {
    this.artifactTypes = artifactTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListArtifactTypesResponse apiListArtifactTypesResponse = (ApiListArtifactTypesResponse) o;
    return Objects.equals(this.artifactTypes, apiListArtifactTypesResponse.artifactTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListArtifactTypesResponse {\n");
    sb.append("    artifactTypes: ").append(toIndentedString(artifactTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

