/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MlMetadataExecutionType;

/**
 * ApiListExecutionTypesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiListExecutionTypesResponse {
  public static final String SERIALIZED_NAME_EXECUTION_TYPES = "execution_types";
  @SerializedName(SERIALIZED_NAME_EXECUTION_TYPES)
  private List<MlMetadataExecutionType> executionTypes = new ArrayList<MlMetadataExecutionType>();

  public ApiListExecutionTypesResponse executionTypes(List<MlMetadataExecutionType> executionTypes) {
    this.executionTypes = executionTypes;
    return this;
  }

  public ApiListExecutionTypesResponse addExecutionTypesItem(MlMetadataExecutionType executionTypesItem) {
    if (this.executionTypes == null) {
      this.executionTypes = new ArrayList<MlMetadataExecutionType>();
    }
    this.executionTypes.add(executionTypesItem);
    return this;
  }

   /**
   * Get executionTypes
   * @return executionTypes
  **/
  @ApiModelProperty(value = "")
  public List<MlMetadataExecutionType> getExecutionTypes() {
    return executionTypes;
  }

  public void setExecutionTypes(List<MlMetadataExecutionType> executionTypes) {
    this.executionTypes = executionTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListExecutionTypesResponse apiListExecutionTypesResponse = (ApiListExecutionTypesResponse) o;
    return Objects.equals(this.executionTypes, apiListExecutionTypesResponse.executionTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executionTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListExecutionTypesResponse {\n");
    sb.append("    executionTypes: ").append(toIndentedString(executionTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

