/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.MlMetadataArtifact;
import org.openapitools.client.model.MlMetadataEvent;
import org.openapitools.client.model.MlMetadataExecution;

/**
 * ApiListEventsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiListEventsResponse {
  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  private List<MlMetadataEvent> events = new ArrayList<MlMetadataEvent>();

  public static final String SERIALIZED_NAME_ARTIFACTS = "artifacts";
  @SerializedName(SERIALIZED_NAME_ARTIFACTS)
  private Map<String, MlMetadataArtifact> artifacts = new HashMap<String, MlMetadataArtifact>();

  public static final String SERIALIZED_NAME_EXECUTIONS = "executions";
  @SerializedName(SERIALIZED_NAME_EXECUTIONS)
  private Map<String, MlMetadataExecution> executions = new HashMap<String, MlMetadataExecution>();

  public ApiListEventsResponse events(List<MlMetadataEvent> events) {
    this.events = events;
    return this;
  }

  public ApiListEventsResponse addEventsItem(MlMetadataEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<MlMetadataEvent>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @ApiModelProperty(value = "")
  public List<MlMetadataEvent> getEvents() {
    return events;
  }

  public void setEvents(List<MlMetadataEvent> events) {
    this.events = events;
  }

  public ApiListEventsResponse artifacts(Map<String, MlMetadataArtifact> artifacts) {
    this.artifacts = artifacts;
    return this;
  }

  public ApiListEventsResponse putArtifactsItem(String key, MlMetadataArtifact artifactsItem) {
    if (this.artifacts == null) {
      this.artifacts = new HashMap<String, MlMetadataArtifact>();
    }
    this.artifacts.put(key, artifactsItem);
    return this;
  }

   /**
   * Get artifacts
   * @return artifacts
  **/
  @ApiModelProperty(value = "")
  public Map<String, MlMetadataArtifact> getArtifacts() {
    return artifacts;
  }

  public void setArtifacts(Map<String, MlMetadataArtifact> artifacts) {
    this.artifacts = artifacts;
  }

  public ApiListEventsResponse executions(Map<String, MlMetadataExecution> executions) {
    this.executions = executions;
    return this;
  }

  public ApiListEventsResponse putExecutionsItem(String key, MlMetadataExecution executionsItem) {
    if (this.executions == null) {
      this.executions = new HashMap<String, MlMetadataExecution>();
    }
    this.executions.put(key, executionsItem);
    return this;
  }

   /**
   * Get executions
   * @return executions
  **/
  @ApiModelProperty(value = "")
  public Map<String, MlMetadataExecution> getExecutions() {
    return executions;
  }

  public void setExecutions(Map<String, MlMetadataExecution> executions) {
    this.executions = executions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListEventsResponse apiListEventsResponse = (ApiListEventsResponse) o;
    return Objects.equals(this.events, apiListEventsResponse.events) &&
        Objects.equals(this.artifacts, apiListEventsResponse.artifacts) &&
        Objects.equals(this.executions, apiListEventsResponse.executions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(events, artifacts, executions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListEventsResponse {\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    artifacts: ").append(toIndentedString(artifacts)).append("\n");
    sb.append("    executions: ").append(toIndentedString(executions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

