/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MlMetadataExecutionType;

/**
 * ApiUpdateExecutionTypeResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class ApiUpdateExecutionTypeResponse {
  public static final String SERIALIZED_NAME_EXECUTION_TYPE = "execution_type";
  @SerializedName(SERIALIZED_NAME_EXECUTION_TYPE)
  private MlMetadataExecutionType executionType = null;

  public ApiUpdateExecutionTypeResponse executionType(MlMetadataExecutionType executionType) {
    this.executionType = executionType;
    return this;
  }

   /**
   * Get executionType
   * @return executionType
  **/
  @ApiModelProperty(value = "")
  public MlMetadataExecutionType getExecutionType() {
    return executionType;
  }

  public void setExecutionType(MlMetadataExecutionType executionType) {
    this.executionType = executionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiUpdateExecutionTypeResponse apiUpdateExecutionTypeResponse = (ApiUpdateExecutionTypeResponse) o;
    return Objects.equals(this.executionType, apiUpdateExecutionTypeResponse.executionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiUpdateExecutionTypeResponse {\n");
    sb.append("    executionType: ").append(toIndentedString(executionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

