/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PathStep;

/**
 * A simple path (e.g. {step{key:\&quot;foo\&quot;}}) can name an artifact in the context of an execution.
 */
@ApiModel(description = "A simple path (e.g. {step{key:\"foo\"}}) can name an artifact in the context of an execution.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class EventPath {
  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<PathStep> steps = new ArrayList<PathStep>();

  public EventPath steps(List<PathStep> steps) {
    this.steps = steps;
    return this;
  }

  public EventPath addStepsItem(PathStep stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<PathStep>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * A simple path (e.g. {step{key:\&quot;foo\&quot;}}) can name an artifact in the context of an execution.
   * @return steps
  **/
  @ApiModelProperty(value = "A simple path (e.g. {step{key:\"foo\"}}) can name an artifact in the context of an execution.")
  public List<PathStep> getSteps() {
    return steps;
  }

  public void setSteps(List<PathStep> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventPath eventPath = (EventPath) o;
    return Objects.equals(this.steps, eventPath.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventPath {\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

