/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A value in properties.
 */
@ApiModel(description = "A value in properties.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class MlMetadataValue {
  public static final String SERIALIZED_NAME_INT_VALUE = "int_value";
  @SerializedName(SERIALIZED_NAME_INT_VALUE)
  private String intValue;

  public static final String SERIALIZED_NAME_DOUBLE_VALUE = "double_value";
  @SerializedName(SERIALIZED_NAME_DOUBLE_VALUE)
  private Double doubleValue;

  public static final String SERIALIZED_NAME_STRING_VALUE = "string_value";
  @SerializedName(SERIALIZED_NAME_STRING_VALUE)
  private String stringValue;

  public MlMetadataValue intValue(String intValue) {
    this.intValue = intValue;
    return this;
  }

   /**
   * Get intValue
   * @return intValue
  **/
  @ApiModelProperty(value = "")
  public String getIntValue() {
    return intValue;
  }

  public void setIntValue(String intValue) {
    this.intValue = intValue;
  }

  public MlMetadataValue doubleValue(Double doubleValue) {
    this.doubleValue = doubleValue;
    return this;
  }

   /**
   * Get doubleValue
   * @return doubleValue
  **/
  @ApiModelProperty(value = "")
  public Double getDoubleValue() {
    return doubleValue;
  }

  public void setDoubleValue(Double doubleValue) {
    this.doubleValue = doubleValue;
  }

  public MlMetadataValue stringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

   /**
   * Get stringValue
   * @return stringValue
  **/
  @ApiModelProperty(value = "")
  public String getStringValue() {
    return stringValue;
  }

  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MlMetadataValue mlMetadataValue = (MlMetadataValue) o;
    return Objects.equals(this.intValue, mlMetadataValue.intValue) &&
        Objects.equals(this.doubleValue, mlMetadataValue.doubleValue) &&
        Objects.equals(this.stringValue, mlMetadataValue.stringValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intValue, doubleValue, stringValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MlMetadataValue {\n");
    sb.append("    intValue: ").append(toIndentedString(intValue)).append("\n");
    sb.append("    doubleValue: ").append(toIndentedString(doubleValue)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

