/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * TODO(martinz): consider moving this inside some message, to avoid having literals directly in apo package.
 */
@JsonAdapter(MlMetadataPropertyType.Adapter.class)
public enum MlMetadataPropertyType {
  
  UNKNOWN("UNKNOWN"),
  
  INT("INT"),
  
  DOUBLE("DOUBLE"),
  
  STRING("STRING");

  private String value;

  MlMetadataPropertyType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MlMetadataPropertyType fromValue(String value) {
    for (MlMetadataPropertyType b : MlMetadataPropertyType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MlMetadataPropertyType> {
    @Override
    public void write(final JsonWriter jsonWriter, final MlMetadataPropertyType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MlMetadataPropertyType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MlMetadataPropertyType.fromValue(value);
    }
  }
}

