/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MlMetadataArtifactStructType;

/**
 * An ordered list of heterogeneous artifact structs. The length of the list is fixed. Each position in the list can have a different type.
 */
@ApiModel(description = "An ordered list of heterogeneous artifact structs. The length of the list is fixed. Each position in the list can have a different type.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class MlMetadataTupleArtifactStructType {
  public static final String SERIALIZED_NAME_ELEMENTS = "elements";
  @SerializedName(SERIALIZED_NAME_ELEMENTS)
  private List<MlMetadataArtifactStructType> elements = new ArrayList<MlMetadataArtifactStructType>();

  public MlMetadataTupleArtifactStructType elements(List<MlMetadataArtifactStructType> elements) {
    this.elements = elements;
    return this;
  }

  public MlMetadataTupleArtifactStructType addElementsItem(MlMetadataArtifactStructType elementsItem) {
    if (this.elements == null) {
      this.elements = new ArrayList<MlMetadataArtifactStructType>();
    }
    this.elements.add(elementsItem);
    return this;
  }

   /**
   * Get elements
   * @return elements
  **/
  @ApiModelProperty(value = "")
  public List<MlMetadataArtifactStructType> getElements() {
    return elements;
  }

  public void setElements(List<MlMetadataArtifactStructType> elements) {
    this.elements = elements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MlMetadataTupleArtifactStructType mlMetadataTupleArtifactStructType = (MlMetadataTupleArtifactStructType) o;
    return Objects.equals(this.elements, mlMetadataTupleArtifactStructType.elements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MlMetadataTupleArtifactStructType {\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

