/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The state of the Execution. The state transitions are   NEW -&gt; RUNNING -&gt; COMPLETE | CACHED | FAILED CACHED means the execution is skipped due to cached results.
 */
@JsonAdapter(MlMetadataExecutionState.Adapter.class)
public enum MlMetadataExecutionState {
  
  UNKNOWN("UNKNOWN"),
  
  NEW("NEW"),
  
  RUNNING("RUNNING"),
  
  COMPLETE("COMPLETE"),
  
  FAILED("FAILED"),
  
  CACHED("CACHED");

  private String value;

  MlMetadataExecutionState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MlMetadataExecutionState fromValue(String value) {
    for (MlMetadataExecutionState b : MlMetadataExecutionState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MlMetadataExecutionState> {
    @Override
    public void write(final JsonWriter jsonWriter, final MlMetadataExecutionState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MlMetadataExecutionState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MlMetadataExecutionState.fromValue(value);
    }
  }
}

