/*
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MlMetadataArtifactStructType;

/**
 * Represents a union of types.
 */
@ApiModel(description = "Represents a union of types.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-29T15:59:29.714+09:00[Asia/Tokyo]")
public class MlMetadataUnionArtifactStructType {
  public static final String SERIALIZED_NAME_CANDIDATES = "candidates";
  @SerializedName(SERIALIZED_NAME_CANDIDATES)
  private List<MlMetadataArtifactStructType> candidates = new ArrayList<MlMetadataArtifactStructType>();

  public MlMetadataUnionArtifactStructType candidates(List<MlMetadataArtifactStructType> candidates) {
    this.candidates = candidates;
    return this;
  }

  public MlMetadataUnionArtifactStructType addCandidatesItem(MlMetadataArtifactStructType candidatesItem) {
    if (this.candidates == null) {
      this.candidates = new ArrayList<MlMetadataArtifactStructType>();
    }
    this.candidates.add(candidatesItem);
    return this;
  }

   /**
   * An artifact struct matches this type if it matches any of the candidates. If candidates is empty, this is a bottom type (matches no artifacts).
   * @return candidates
  **/
  @ApiModelProperty(value = "An artifact struct matches this type if it matches any of the candidates. If candidates is empty, this is a bottom type (matches no artifacts).")
  public List<MlMetadataArtifactStructType> getCandidates() {
    return candidates;
  }

  public void setCandidates(List<MlMetadataArtifactStructType> candidates) {
    this.candidates = candidates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MlMetadataUnionArtifactStructType mlMetadataUnionArtifactStructType = (MlMetadataUnionArtifactStructType) o;
    return Objects.equals(this.candidates, mlMetadataUnionArtifactStructType.candidates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(candidates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MlMetadataUnionArtifactStructType {\n");
    sb.append("    candidates: ").append(toIndentedString(candidates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

